crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crmbasic/', include('crm_app.urls'), name='crm_app'),
    url(r'^accounts/login/$', auth_views.login,{'template_name':'crm_app/login.html'}, name='login'),
    url(r'^crmapi/', include('crm_api.urls'), name='crm_api'),

]

crm_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from crm_app import views

urlpatterns = [
#    url(r'^$', views.home),
    url(r'ajaxcall/', views.dynamic_dropdown),
    url(r'addmeeting/', views.add_meeting, name='add_meeting'),
    url(r'addproject/', views.add_project, name='add_project'),
    url(r'addcontact/', views.add_contact, name='add_contact'),
    url(r'addaccount/', views.add_account, name='add_account'),
    url(r'viewaccount/(?P<company_name>[a-zA-Z]+)/$', views.view_account, name='view_account'),
    url(r'viewallaccounts/', views.view_all_accounts, name='view_all_accounts'),
    # url(r'viewmeeting/(?P<company_name>[a-zA-Z]+)/(?P<date>[a-zA-Z0-9][ A-Za-z0-9_-]*)/$', views.view_meeting, name='view_meeting'),
    url(r'viewmeeting/(?P<company_name>[a-zA-Z]+)/$', views.view_meeting, name='view_meeting'),
    url(r'viewallmeetings/', views.view_all_meetings, name='view_all_meetings'),
    url(r'viewcontact/(?P<company_name>[a-zA-Z]+)/(?P<contact_id>\d+)$', views.view_contact, name='view_contact'),
    url(r'viewallcontacts/', views.view_all_contacts, name='view_all_contacts'),
    url(r'viewproject/(?P<company_name>[a-zA-Z]+)/(?P<project_name>[(a-zA-Z) (a-zA-Z)]+)$', views.view_project, name='view_project'),
    url(r'viewallprojects/', views.view_all_projects, name='view_all_projects'),
    url(r'home/', views.home),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^changepasswordlogin/', views.change_password_login, name='change_password_login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

crm_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


# Create your models here.

class user(models.Model):
    user_id = models.OneToOneField('User', on_delete=models.CASCADE, db_column='user_id')

    class Meta:
        db_table = 'User'


class Account(models.Model):
    company_name = models.CharField(primary_key=True, max_length=200, db_column='Company name')
    status = models.TextField(db_column='Status', blank=False, null=False)
    category = models.TextField(db_column='Category', blank=False, null=False)

    class Meta:
        db_table = 'Account'

    def __str__(self):
        return '%s' % (self.company_name)


class Contact(models.Model):
    account_company_name = models.ForeignKey('Account', on_delete=models.CASCADE, db_column='account_companyname')
    name = models.CharField(db_column='Contact name', max_length=120, blank=False, null=False)
    email = models.EmailField(unique= True, db_column='Email', blank=False, null=False)
    phone = models.CharField(unique=True, max_length=10, validators=[RegexValidator(r'^\d{10}|(\d{5}[\-]\d{6})$')],
                             db_column='Phone', blank=False, null=False) #'\d{10}+|\d{5}([- ]*)\d{6}'  it worked - '\d{10}'
                            # complete regex : ((\+*)((0[ -]+)*|(91 )*)(\d{12}+|\d{10}+))|\d{5}([- ]*)\d{6}
    notes = models.TextField()

    class Meta:
        db_table = 'Contact'
        unique_together = ('email','phone')

    def __str__(self):
        return '%s' % (self.name)

class Project(models.Model):
    account_company_name = models.ForeignKey('Account', on_delete=models.CASCADE, db_column='account_companyname')
    name = models.CharField(db_column='Project name', max_length=120, blank=False, null=False)
    notes = models.TextField()
    status = models.TextField(db_column='Status', blank=False, null=False)

    class Meta:
        db_table = 'Project'
        unique_together = ('account_company_name','name')

    def __str__(self):
        return '%s' % (self.name)


class Meeting(models.Model):
    account_company_name = models.ForeignKey('Account', on_delete=models.CASCADE, db_column='account_companyname')
    contact_id = models.ForeignKey('Contact', on_delete=models.CASCADE, db_column='contact_id')
    project_id = models.ForeignKey('Project', on_delete=models.CASCADE, db_column='project_id')
    date = models.DateTimeField(db_column='Date', null=False)
    notes = models.TextField(blank=False, null=False)

    class Meta:
        db_table = 'Meeting'
        unique_together=('date','account_company_name')

crm_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from time import strftime, time

from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect

# Create your views here.
from django.template import RequestContext
from django.template.context_processors import request, csrf
from django.contrib import messages
from crm_app.form import *
from .models import *


def home(request):
    return render(request, 'crm_app/login.html')


def add_account(request):
    args = {}
    args.update(csrf(request))
    if request.method == 'POST':
        form = AccountForm(request.POST)
        args['form'] = form
        if form.is_valid():
            print form
            args['msg'] = messages.success(request, 'ACCOUNT ADDED SUCCESSFULLY')
            form.save()  # save account to database if form is valid
            return HttpResponseRedirect('/crmbasic/home/')
        else:
            args['form'] = AccountForm()
            args['msg'] = messages.error(request, 'SOMETHING WENT WRONG !! TRY AGAIN.')
            return render_to_response('crm_app/add_account.html', args, RequestContext(request))
    args['form'] = AccountForm()
    return render_to_response('crm_app/add_account.html', args, RequestContext(request))


def add_contact(request):
    args = {}
    args.update(csrf(request))
    if request.method == 'POST':
        form = ContactForm(request.POST)
        args['form'] = form
        if form.is_valid():
            print form
            args['msg'] = messages.success(request, 'CONTACT ADDED SUCCESSFULLY')
            form.save()  # save contact to database if form is valid
            cont_obj = Contact.objects.all().values()
            print(cont_obj)
            return HttpResponseRedirect('/crmbasic/home/')
        else:
            args['form'] = ContactForm()
            args['msg'] = messages.error(request, 'SOMETHING WENT WRONG !! TRY AGAIN.')
            print("here it comes")
            return render_to_response('crm_app/add_contact.html', args, RequestContext(request))
    args['form'] = ContactForm()
    return render_to_response('crm_app/add_contact.html', args, RequestContext(request))


def add_project(request):
    args = {}
    args.update(csrf(request))
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        args['form'] = form
        if form.is_valid():
            print form
            args['msg'] = messages.success(request, 'CONTACT ADDED SUCCESSFULLY')
            form.save()  # save contact to database if form is valid
            return HttpResponseRedirect('/crmbasic/home/')
        else:
            args['form'] = ProjectForm()
            args['msg'] = messages.error(request, 'SOMETHING WENT WRONG !! TRY AGAIN.')
            return render_to_response('crm_app/add_project.html', args, RequestContext(request))
    args['form'] = ProjectForm()
    return render_to_response('crm_app/add_project.html', args, RequestContext(request))


@login_required
def add_meeting(request):
    args = {}
    args.update(csrf(request))
    if request.method == 'POST':
        print(request.user)
        form = MeetingForm(request.POST)
        args['form'] = form

        # form.data['datetimevalue']
        if form.is_valid():
            obj = Meeting()
            print form, "make it work"

            print request.POST.get('datetimevalue')
            obj.date = request.POST.get('datetimevalue')
            obj.account_company_name = form.cleaned_data['account_company_name']
            obj.notes = form.cleaned_data['notes']
            obj.project_id = form.cleaned_data['project_id']
            obj.contact_id = form.cleaned_data['contact_id']
            args['msg'] = messages.success(request, 'CONTACT ADDED SUCCESSFULLY')
            obj.save()  # save contact to database if form is valid
            return HttpResponseRedirect('/crmbasic/home/')
        else:
            args['form'] = MeetingForm()
            args['msg'] = messages.error(request, 'SOMETHING WENT WRONG !! TRY AGAIN.')
            print("here it comes")
            return render_to_response('crm_app/add_meeting.html', args, RequestContext(request))
    args['form'] = MeetingForm()
    return render_to_response('crm_app/add_meeting.html', args, RequestContext(request))


def dynamic_dropdown(request):
    if request.is_ajax():
        todo_items = ['Mow Lawn', 'Buy Groceries', ]
        # print(todo_items)
        com_name = request.GET.get('Item')
        name_email_list = Contact.objects.filter(account_company_name__company_name__contains=com_name).values_list(
            'name', 'email')
        name_email_list = [i[0] + '(' + i[1] + ')' for i in name_email_list]
        project_list = Project.objects.filter(account_company_name__company_name__contains=com_name,
                                              status__exact='active').values_list('name')
        project_list = [i[0] for i in project_list]
        data = json.dumps({'contact_list': name_email_list, 'project_list': project_list})

        return HttpResponse(data, content_type='application/json')
    else:
        raise Http404


def view_account(request, company_name):
    args = {}
    if request.method == 'GET':
        com_name = company_name
        print(com_name)
        obj = Account.objects.get(company_name=com_name)
        contact_list = Contact.objects.filter(account_company_name__company_name=com_name).values_list()
        contact_ids_list = [i[0] for i in contact_list]
        contact_names = [i[2] for i in contact_list]
        project_list = Project.objects.filter(account_company_name__company_name=com_name).values_list()
        project_ids_list = [i[0] for i in project_list]
        project_names = [i[2] for i in project_list]
        meeting_list = Meeting.objects.filter(account_company_name__company_name=com_name,
                                              contact_id_id__in=contact_ids_list,
                                              project_id_id__in=project_ids_list).values_list()
        meeting_notes = [i[1] for i in meeting_list]

        args['contact_list'] = contact_list
        args['contact_names'] = contact_names
        args['project_list'] = project_list
        args['project_names'] = project_names
        args['meeting_list'] = meeting_list
        args['meeting_notes'] = meeting_notes
        args['account_obj'] = obj
        return render_to_response('crm_app/view_account.html', args, RequestContext(request))
    raise Http404


def view_all_accounts(request):
    args = {}
    if request.method == 'GET':
        all_accounts = Account.objects.all().order_by('status')
        args['all_accounts'] = all_accounts
        return render_to_response('crm_app/view_all_accounts.html', args, RequestContext(request))
    raise Http404


def view_all_meetings(request):
    args = {}
    if request.method == 'GET':
        all_meetings = Meeting.objects.all().order_by('date')[::-1]
        args['all_meetings'] = all_meetings
        return render_to_response('crm_app/view_all_meetings.html', args, RequestContext(request))
    raise Http404


# def view_meeting(request, company_name, date):
def view_meeting(request, company_name):
    args = {}
    if request.method == 'GET':
        # print(date)
        meeting_info = Meeting.objects.filter(account_company_name__company_name=company_name)
        args['meeting_info'] = meeting_info
        return render_to_response('crm_app/view_meeting.html', args, RequestContext(request))
    raise Http404


def view_all_contacts(request):
    args = {}
    if request.method == 'GET':
        all_contacts = Contact.objects.all()
        args['all_contacts'] = all_contacts
        return render_to_response('crm_app/view_all_contacts.html', args, RequestContext(request))
    raise Http404


def view_contact(request, company_name, contact_id):
    args = {}
    if request.method == 'GET':
        contact_info = Contact.objects.filter(account_company_name__company_name=company_name, id=contact_id)
        meeting_info  = Meeting.objects.filter(account_company_name__company_name=company_name, contact_id=contact_id)
        args['contact_info'] = contact_info
        args['meeting_info'] = meeting_info
        return render_to_response('crm_app/view_contact.html', args, RequestContext(request))
    raise Http404


def view_all_projects(request):
    args = {}
    if request.method == 'GET':
        all_projects = Project.objects.all().values_list('account_company_name', 'name').order_by('name')
        args['all_projects'] = all_projects
        for i in all_projects:
            print(i)
        return render_to_response('crm_app/view_all_projects.html', args, RequestContext(request))
    raise Http404


def view_project(request, company_name, project_name):
    args = {}
    if request.method == 'GET':
        project_info = Project.objects.filter(account_company_name__company_name=company_name, name=project_name)
        contact_info = Contact.objects.filter(account_company_name__company_name=company_name)
        proj_lst = [i.id for i in project_info]
        con_lst = [i.id for i in contact_info]

        meeting_info = Meeting.objects.filter(account_company_name__company_name=company_name,
                                              project_id__in=proj_lst, contact_id__in=con_lst)
        print("more info")
        args['company_name'] = company_name
        args['project_info'] = project_info
        args['contact_info'] = contact_info
        args['meeting_info'] = meeting_info
        for i in meeting_info:
            print(i)

        return render_to_response('crm_app/view_project.html', args, RequestContext(request))
    raise Http404

crm_app/templates/crm_app/add_meeting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MEETING</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css">

</head>
<body>
{#<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>#}
{#<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>#}
{#<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet"#}
{#      type="text/css"/>#}
<h3>have fun</h3>

   {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <a href="{% url 'logout' %}">logout</a>
    {% endif %}

{% if msg %}
    <ul class="messages">
        {% for message in msg %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form class="login-form" method="post" action="/crmbasic/addmeeting/">{% csrf_token %}
    <label for="accountfield_id">Account Name:</label>
    <p id='accountfield_id'>{{ form.account_company_name }}
    </p>
    <input id="id_accbutton" type="button" value="View Account"><br>
    <label for="contactfield_id">Contact:</label>
    <p id='contactfield_id'>{{ form.contact_id }}
    </p>
    <label for="projectfield_id">Project Name:</label>
    <p id='projectfield_id'>{{ form.project_id }}
    </p>
    <div class="container">
        <div class="col-sm-6" style="height:130px;">
            <div class="form-group">
                <label for="datetimepicker_div">Date:</label>
                <div class='input-group date' id='datetimepicker_div'>
                    <input type='text' id="id_datetimepicker" name='datetimevalue' class="form-control"/>
                    <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar">
                    </span>
                </span>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $(document).ready(function () {

                // AJAX GET
                $("#id_account_company_name").change(function () {
                    $.ajax({
                        type: "GET",
                        url: "/crmbasic/ajaxcall/",
                        datatype: "json",
                        data: "Item=" + $("#id_account_company_name").val(),
                        success: function (data) {
                            alert(data.contact_list[0].toString())
                            if (data.contact_list.length == 0) {
                                $('#contactfield_id').html('<select name="contact_id" required id="id_contact_id">' +
                                    '<option value="1">No Record Found</option></select>');
                            }
                            if (data.project_list.length == 0) {
                                $('#projectfield_id').html('<select name="contact_id" required id="id_contact_id">' +
                                    '<option value="1">No Record Found</option></select>');
                            }
                            else {

                                $('#contactfield_id').html('<select name="contact_id" required id="id_contact_id">' +
                                    '<option value>Select value</option>');
                                for (i = 1; i <= data.contact_list.length; i++) {
                                    alert('inside for');
                                    $('#id_contact_id').append('<option value="' + i.toString() + '">' + data.contact_list[i - 1] + '</option>');
                                }

                                $('#projectfield_id').html('<select name="project_id" required id="id_project_id">' +
                                    '<option value>Select value</option>');
                                for (i = 1; i <= data.project_list.length; i++) {
                                    alert('inside otherfor');
                                    $('#id_project_id').append('<option value="' + i.toString() + '">' + data.project_list[i - 1] + '</option>');
                                }
                                $('#id_contact_id').append('</select>');
                                $('#id_project_id').append('</select>');

                            }
                        }
                    });

                });
            });
            {#document.ready() ends here#}

            $(function () {
                $('#datetimepicker_div').datetimepicker({
                    viewMode: 'years',
                    format: 'YYYY-MM-DD HH:mm'
                });
            });
            $("#id_accbutton").click(function () {
                alert($("#id_account_company_name option:selected").val())
                window.location = "/crmbasic/viewaccount/" + $("#id_account_company_name option:selected").val()
            });
        </script>
    </div>
    <label for="meetingfield_id">Notes:</label>
    <p id='meetingfield_id'>{{ form.notes }}
    </p>
    <input type="submit" value="ADD MEETING">
</form>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js">

</script>

{#<script>#}
{#    $(function () {#}
{#        $(".datepicker").datepicker({#}
{#            changeMonth: true,#}
{#            changeYear: true,#}
{#            yearRange: "2015:2100",#}
{#            // You can put more options here.#}
{##}
{#        });#}
{#    });#}
{#</script>#}
</body>
</html>

crm_app/templates/crm_app/add_project.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PROJECT</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

</head>
<body>
<h3>have fun</h3>
{% if msg %}
    <ul class="messages">
        {% for message in msg %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form class="login-form" method="post" action="/crmbasic/addproject/">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="ADD PROJECT">
</form>
</body>
</html>

crm_app/templates/crm_app/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
</body>
</html>

crm_app/templates/crm_app/chat_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{{ form }}
</body>
</html>

crm_app/templates/crm_app/gallery.html
{% extends "crm_app/base.html" %}
{% load staticfiles %}
{#<html>#}
{#<head lang="en">#}
{#    <meta charset="UTF-8">#}
{#    <title>LOGOUT</title>#}
{##}
{#    <link rel="stylesheet" href="{% static 'shwekd/css/materialize.css' %}">#}
{##}
{#    <link rel="stylesheet" href="{% static 'shwekd/css/materialize.min.css' %}">#}
{##}
{##}
{#    <link rel="stylesheet" href="{% static 'shwekd/js/materialize.min.js' %}">#}
{##}
{#    <link rel="stylesheet" href="{% static 'shwekd/js/materialize.js' %}">#}

{#</head>#}
{#{% block head_main %}#}
{##}
{#    <link href="{% static "crm_app/css/assets/css/bootstrapTheme.css"%}" rel="stylesheet">#}
{#    <link href="{% static "crm_app/css/assets/css/custom.css"%}" rel="stylesheet">#}
{##}
{#    <!-- Owl Carousel Assets -->#}
{#    <link href="{% static "crm_app/css/owl-carousel/owl.carousel.css"%}" rel="stylesheet">#}
{#    <link href="{% static "crm_app/css/owl-carousel/owl.theme.css"%}" rel="stylesheet">#}
{##}
{#    <link href="{% static "crm_app/css/assets/js/google-code-prettify/prettify.css"%}" rel="stylesheet">#}
{##}
{##}
{#    {%  endblock %}#}

{% block main %}
{#<style>#}
{#    img .materialboxed .intialized{#}
{##}
{#        height: 225px;#}
{##}
{#    }#}
{#    </style>#}



    <body>

    <script src="{% static "crm_app/css/assets/js/jquery-1.9.1.min.js" %}"></script>
    <script src="{% static "crm_app/css/owl-carousel/owl.carousel.js" %}"></script>


    <script src="{% static "crm_app/css/assets/js/bootstrap-collapse.js" %}"></script>
    <script src="{% static "crm_app/css/assets/js/bootstrap-transition.js" %}"></script>
    <script src="{% static "crm_app/css/assets/js/bootstrap-tab.js" %}"></script>

    <script src="{% static "crm_app/css/assets/js/google-code-prettify/prettify.js" %}"></script>
    <script src="{% static "crm_app/css/assets/js/application.js" %}"></script>

    <!-- Floating Action Button -->
                   <div class="fixed-action-btn" style="top: 90px; right: 15px;">
                       <a class="btn-floating btn-large red">
                         <i class="large mdi-action-language"></i>
                       </a>
                       <ul>
                           <li><a href="/ca_engg/team/" class="btn-floating pink tooltipped" data-position="left" data-delay="50" data-tooltip="TEAM"><i class="large mdi-social-group"></i></a></li>
                           <li><a href="/ca_engg/stories/" class="btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="SUCCESS STORIES"><i class="large mdi-hardware-security"></i></a></li>
                         <li><a href="/ca_engg/training/" class="btn-floating orange tooltipped" data-position="left" data-delay="50" data-tooltip="TRAINING"><i class="large mdi-hardware-laptop-chromebook"></i></a></li>
                           <li><a href="/ca_engg/our_niche/" class="btn-floating pink tooltipped" data-position="left" data-delay="50" data-tooltip="OUR NICHE"><i class="large mdi-image-center-focus-strong"></i></a></li>
                         <li><a href="/ca_engg/live_projects/" class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="LIVE PROJECTS"><i class="large mdi-editor-insert-invitation"></i></a></li>
                                     <li><a href="/ca_engg/careers/" class="btn-floating pink tooltipped" data-position="left" data-delay="50" data-tooltip="CAREER"><i class="large mdi-social-person-outline"></i></a></li>
       <li><a href="http://www.consultadd.com" target="_blank" class="btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="ABOUT US"><i class="large mdi-action-account-balance-wallet"></i></a></li>
                       </ul>
                   </div>
                   <!-- Floating Action Button -->

{#    <div class="material-placeholder">#}
<div class="row" style="margin-top: 20px;margin-left: 20px">
    <div class="col s12 m4">
        <img class="materialboxed intialized" width="300" src="{%  static "crm_app/images/gallery_img/img_1.jpg" %}" alt="sample" data-caption="ADD CAPTION HERE">

<BR>
        <img class="materialboxed intialized" width="300" height="225" src="{%  static "crm_app/images/gallery_img/img_2.jpg" %}" alt="sample" data-caption="ADD CAPTION HERE">
</div>

    <div class="col s12 m4">
  <img class="materialboxed intialized" width="300" height="225" src="{%  static "crm_app/images/gallery_img/img_3.jpg" %}" alt="sample" data-caption="ADD CAPTION HERE">
<BR>
        <img class="materialboxed intialized" width="300" height="225" src="{%  static "crm_app/images/gallery_img/img_4.jpg" %}" alt="sample" data-caption="ADD CAPTION HERE">
{#</div>#}
</div>
</div>

</body>
{% endblock %}
{#</html>#}

crm_app/templates/crm_app/profile.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>USER PROFILE</title>


    <link rel="stylesheet" href="{% static 'crm_app/css/materialize.css' %}">

    <link rel="stylesheet" href="{% static 'crm_app/css/materialize.min.css' %}">


    <link rel="stylesheet" href="{% static 'crm_app/js/materialize.min.js' %}">

    <link rel="stylesheet" href="{% static 'crm_app/js/materialize.js' %}">
</head>
<body>

<h2 class="waves-light" style="background-color: lightseagreen; margin-left: 750px">USER PROFILE</h2>
<br>

<div style="height: 30px; width: 300px; margin-left: 800px">
    <div>
        <form action="{% url "profile_image_upload" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            {#                <form method="post" action="/fmar/profile/">{% csrf_token %}#}
            {#                    {% for field in form %}#}
            {##}
            {#            <h2 style="color:black;background-color: yellow">{{ field.label }}</h2>#}
            {#                        {{ field }}<br>#}
            {##}
            {##}
            {#                    {% endfor %}#}
            <br><input class="btn waves-effect waves-light" type="submit" value="GO"><i
                class="material-icons right"></i>
        </form>
    </div>
</div>
</body>
</html>

crm_app/templates/crm_app/view_all_accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View All Accounts</title>
</head>
<body>
<h3>have fun</h3>
{% if msg %}
    <ul class="messages">
        {% for message in msg %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<br>
<b>ACCOUNTS LIST:</b><br>
{% for i in all_accounts %}
<pre>
    <a href="{% url 'view_account' company_name=i.company_name %}"><span><t><b>{{ i.company_name }}</b></t></span></a>
    <span><t><b>{{ i.category }}</b></t></span>
    <span><t><b>{{ i.status }}</b></t></span>
    <br>
    </pre>
{% endfor %}
<br>
</body>
</html>

crm_app/templates/crm_app/view_meeting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Meeting</title>
</head>
<body>
<h3>have fun</h3>
{% if msg %}
<ul class="messages">
    {% for message in msg %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<br>
<b>MEETING LIST:</b><br>
{% for i in meeting_info %}
    <pre>
        <span><t><i>{{ i.date }}</i></t></span><br>
        <span><t><i>{{ i.notes }}</i></t></span><br>
        <a href="{% url 'view_account' company_name=i.account_company_name %}"><span><t><b>{{ i.account_company_name }}</b></t></span></a><br>
        <a href="{% url 'view_contact' company_name=i.account_company_name id=i.contact_id_id %}"><span><t><i>{{ i.contact_id }}</i></t></span></a><br>
        <br>
    </pre>
{% endfor %}
<br>
</body>
</html>